// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vquxyeqhjzoiknultdji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxdXh5ZXFoanpvaWtudWx0ZGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyMTU2OTUsImV4cCI6MjA1MTc5MTY5NX0.MfdwqTu-PUukzuiEai2aDInl2s9m0NMKU5XZXb0JpqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);